name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v4.1.1
      - uses: Saber2pr/wiki-builder@v0.0.61
        with:
          basename: /todolist-pro
          iconUrl: //saber2pr.top/MyWeb/resource/image/todolist-logo.png
          
