name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v4.1.1
      - uses: Saber2pr/wiki-builder@v0.0.68
        with:
          basename: /todolist-pro
          gaId: G-6CLMYWGQBH
          iconUrl: //saber2pr.top/MyWeb/resource/image/todolist-logo.png
          expandAllMenu: on
          title: Todolist TreeView
          keywords: todolist,smalltask,tree,manager,vscode-extension,web-app
          description: TodoList TreeView Editor. Check your todo list with a TreeView