name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Saber2pr/wiki-builder@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
